### ISSUE TITLE
error while run bot

### ISSUE THREAD

**Issue by BryanAlberts** [inadvertently/Blame#4]
![image](https://github.com/inadvertently/Blame-Discord-Bot/assets/59321692/463f9c73-581a-42b3-91b4-379bd8671e26)

**Comment by inadvertently** [comment]
``pip install motor``

"async" mongodb driver which the bot depends on

**Comment by BryanAlberts** [comment]
```
Desktop\Blame-Discord-Bot-main>pip install motor
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: motor in c:\program files\python312\lib\site-packages (3.4.0)
Requirement already satisfied: pymongo<5,>=4.5 in c:\program files\python312\lib\site-packages (from motor) (4.7.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\program files\python312\lib\site-packages (from pymongo<5,>=4.5->motor) (2.6.1)
```





```
Desktop\Blame-Discord-Bot-main>python main.py
Traceback (most recent call last):
  File "C:\Users\sixpa\Desktop\Blame-Discord-Bot-main\main.py", line 1, in <module>
    import discord, os,time, socket, os,logging,asyncio, motor.motor_asyncio, Core.help as _init, db.database as connections
  File "C:\Users\sixpa\Desktop\Blame-Discord-Bot-main\Core\help.py", line 6, in <module>
    import button_paginator as pg
ModuleNotFoundError: No module named 'button_paginator'
```
